// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AttestationCheckingParameters is an autogenerated mock type for the AttestationCheckingParameters type
type AttestationCheckingParameters struct {
	mock.Mock
}

// EnableChecking provides a mock function with given fields:
func (_m *AttestationCheckingParameters) EnableChecking() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Frequency provides a mock function with given fields:
func (_m *AttestationCheckingParameters) Frequency() uint32 {
	ret := _m.Called()

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// RequiredNumberOfMessages provides a mock function with given fields:
func (_m *AttestationCheckingParameters) RequiredNumberOfMessages() uint32 {
	ret := _m.Called()

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

type mockConstructorTestingTNewAttestationCheckingParameters interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttestationCheckingParameters creates a new instance of AttestationCheckingParameters. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttestationCheckingParameters(t mockConstructorTestingTNewAttestationCheckingParameters) *AttestationCheckingParameters {
	mock := &AttestationCheckingParameters{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
