// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	channelconfig "github.com/hyperledger/fabric/common/channelconfig"
	mock "github.com/stretchr/testify/mock"
)

// AttestationCheckingParametersProvider is an autogenerated mock type for the AttestationCheckingParametersProvider type
type AttestationCheckingParametersProvider struct {
	mock.Mock
}

// AttestationCheckingParameters provides a mock function with given fields:
func (_m *AttestationCheckingParametersProvider) AttestationCheckingParameters() channelconfig.AttestationCheckingParameters {
	ret := _m.Called()

	var r0 channelconfig.AttestationCheckingParameters
	if rf, ok := ret.Get(0).(func() channelconfig.AttestationCheckingParameters); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(channelconfig.AttestationCheckingParameters)
		}
	}

	return r0
}

type mockConstructorTestingTNewAttestationCheckingParametersProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttestationCheckingParametersProvider creates a new instance of AttestationCheckingParametersProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttestationCheckingParametersProvider(t mockConstructorTestingTNewAttestationCheckingParametersProvider) *AttestationCheckingParametersProvider {
	mock := &AttestationCheckingParametersProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
