// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AttestationMessageSender is an autogenerated mock type for the AttestationMessageSender type
type AttestationMessageSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: blockNUmber, mptHead
func (_m *AttestationMessageSender) Send(blockNUmber uint64, mptHead []byte) error {
	ret := _m.Called(blockNUmber, mptHead)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []byte) error); ok {
		r0 = rf(blockNUmber, mptHead)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAttestationMessageSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttestationMessageSender creates a new instance of AttestationMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttestationMessageSender(t mockConstructorTestingTNewAttestationMessageSender) *AttestationMessageSender {
	mock := &AttestationMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
